DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS professor CASCADE;
DROP TABLE IF EXISTS class CASCADE;
DROP TABLE IF EXISTS enrol CASCADE;

CREATE TABLE IF NOT EXISTS student (
    student_id SERIAL NOT NULL,
    code INT4 NOT NULL,
    job VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    dept VARCHAR(255) NOT NULL,
    ID VARCHAR(255) NOT NULL,
    PW VARCHAR(255) NOT NULL,
    grade INT4 NOT NULL,
    point INT4 NOT NULL,
    PRIMARY KEY (student_id)
);

CREATE TABLE IF NOT EXISTS professor ( 
	professor_id SERIAL NOT NULL,
	code INT4 NOT NULL,
    job VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    dept VARCHAR(255) NOT NULL,
    ID VARCHAR(255) NOT NULL,
    PW VARCHAR(255) NOT NULL,
    PRIMARY KEY (professor_id)
);

CREATE TABLE IF NOT EXISTS class ( 
	class_id SERIAL NOT NULL,
	code INT4 NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	p_name VARCHAR(255) NOT NULL, 
	dept VARCHAR(255) NOT NULL, 
	location VARCHAR(255) NOT NULL,
	limit_num INT4 NOT NULL, 
	current_num INT4 NOT NULL, 
	point INT4 NOT NULL, 
	grade INT4 NOT NULL,
	PRIMARY KEY (class_id) 
);

CREATE TABLE IF NOT EXISTS enrol (
    code SERIAL NOT NULL,
    class_id INT4 NOT NULL,
    student_id INT4 NOT NULL,
    PRIMARY KEY (code)
);


ALTER TABLE enrol DROP CONSTRAINT IF EXISTS FK_CLASS_CODE;
ALTER TABLE enrol DROP CONSTRAINT IF EXISTS FK_STUDENT_CODE;

ALTER TABLE enrol ADD CONSTRAINT FK_CLASS_CODE FOREIGN KEY (class_id) REFERENCES class;
ALTER TABLE enrol ADD CONSTRAINT FK_STUDENT_CODE FOREIGN KEY (student_id) REFERENCES student;
